version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=java'